IF DB_ID('tpcc') IS NOT NULL
BEGIN
    ALTER DATABASE tpcc SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE tpcc;
END;

IF EXISTS (SELECT * FROM sys.sql_logins WHERE name = 'tpcc')
BEGIN
    DROP LOGIN tpcc;
END;
